import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Shared/NavBar";
import FriendsProvider from "./contexts/FriendsProvider";
import { ToastContainer } from "react-toastify";
import Footer from "./components/Shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme=""
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={geistSans.className}>
        <main className="max-w-7xl mx-auto">
          <FriendsProvider>
            <NavBar />
            {children}
            <Footer/>
             <ToastContainer />
          </FriendsProvider>
        </main>
      </body>
    </html>
  );
}
